# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/teun/Documents/C++/engine/engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/teun/Documents/C++/engine/engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teun/Documents/C++/engine/engine/CMakeFiles /home/teun/Documents/C++/engine/engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teun/Documents/C++/engine/engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

game/display/sprite/sprite.o: game/display/sprite/sprite.cc.o

.PHONY : game/display/sprite/sprite.o

# target to build an object file
game/display/sprite/sprite.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/sprite/sprite.cc.o
.PHONY : game/display/sprite/sprite.cc.o

game/display/sprite/sprite.i: game/display/sprite/sprite.cc.i

.PHONY : game/display/sprite/sprite.i

# target to preprocess a source file
game/display/sprite/sprite.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/sprite/sprite.cc.i
.PHONY : game/display/sprite/sprite.cc.i

game/display/sprite/sprite.s: game/display/sprite/sprite.cc.s

.PHONY : game/display/sprite/sprite.s

# target to generate assembly for a file
game/display/sprite/sprite.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/sprite/sprite.cc.s
.PHONY : game/display/sprite/sprite.cc.s

game/display/spritebox/spritebox.o: game/display/spritebox/spritebox.cc.o

.PHONY : game/display/spritebox/spritebox.o

# target to build an object file
game/display/spritebox/spritebox.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/spritebox/spritebox.cc.o
.PHONY : game/display/spritebox/spritebox.cc.o

game/display/spritebox/spritebox.i: game/display/spritebox/spritebox.cc.i

.PHONY : game/display/spritebox/spritebox.i

# target to preprocess a source file
game/display/spritebox/spritebox.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/spritebox/spritebox.cc.i
.PHONY : game/display/spritebox/spritebox.cc.i

game/display/spritebox/spritebox.s: game/display/spritebox/spritebox.cc.s

.PHONY : game/display/spritebox/spritebox.s

# target to generate assembly for a file
game/display/spritebox/spritebox.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/spritebox/spritebox.cc.s
.PHONY : game/display/spritebox/spritebox.cc.s

game/display/transform/transform.o: game/display/transform/transform.cc.o

.PHONY : game/display/transform/transform.o

# target to build an object file
game/display/transform/transform.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/transform/transform.cc.o
.PHONY : game/display/transform/transform.cc.o

game/display/transform/transform.i: game/display/transform/transform.cc.i

.PHONY : game/display/transform/transform.i

# target to preprocess a source file
game/display/transform/transform.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/transform/transform.cc.i
.PHONY : game/display/transform/transform.cc.i

game/display/transform/transform.s: game/display/transform/transform.cc.s

.PHONY : game/display/transform/transform.s

# target to generate assembly for a file
game/display/transform/transform.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/transform/transform.cc.s
.PHONY : game/display/transform/transform.cc.s

game/display/window/window.o: game/display/window/window.cc.o

.PHONY : game/display/window/window.o

# target to build an object file
game/display/window/window.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/window/window.cc.o
.PHONY : game/display/window/window.cc.o

game/display/window/window.i: game/display/window/window.cc.i

.PHONY : game/display/window/window.i

# target to preprocess a source file
game/display/window/window.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/window/window.cc.i
.PHONY : game/display/window/window.cc.i

game/display/window/window.s: game/display/window/window.cc.s

.PHONY : game/display/window/window.s

# target to generate assembly for a file
game/display/window/window.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/display/window/window.cc.s
.PHONY : game/display/window/window.cc.s

game/game.o: game/game.cc.o

.PHONY : game/game.o

# target to build an object file
game/game.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/game.cc.o
.PHONY : game/game.cc.o

game/game.i: game/game.cc.i

.PHONY : game/game.i

# target to preprocess a source file
game/game.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/game.cc.i
.PHONY : game/game.cc.i

game/game.s: game/game.cc.s

.PHONY : game/game.s

# target to generate assembly for a file
game/game.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/game.cc.s
.PHONY : game/game.cc.s

game/gameobjects/level/level.o: game/gameobjects/level/level.cc.o

.PHONY : game/gameobjects/level/level.o

# target to build an object file
game/gameobjects/level/level.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gameobjects/level/level.cc.o
.PHONY : game/gameobjects/level/level.cc.o

game/gameobjects/level/level.i: game/gameobjects/level/level.cc.i

.PHONY : game/gameobjects/level/level.i

# target to preprocess a source file
game/gameobjects/level/level.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gameobjects/level/level.cc.i
.PHONY : game/gameobjects/level/level.cc.i

game/gameobjects/level/level.s: game/gameobjects/level/level.cc.s

.PHONY : game/gameobjects/level/level.s

# target to generate assembly for a file
game/gameobjects/level/level.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gameobjects/level/level.cc.s
.PHONY : game/gameobjects/level/level.cc.s

game/gameobjects/player/player.o: game/gameobjects/player/player.cc.o

.PHONY : game/gameobjects/player/player.o

# target to build an object file
game/gameobjects/player/player.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gameobjects/player/player.cc.o
.PHONY : game/gameobjects/player/player.cc.o

game/gameobjects/player/player.i: game/gameobjects/player/player.cc.i

.PHONY : game/gameobjects/player/player.i

# target to preprocess a source file
game/gameobjects/player/player.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gameobjects/player/player.cc.i
.PHONY : game/gameobjects/player/player.cc.i

game/gameobjects/player/player.s: game/gameobjects/player/player.cc.s

.PHONY : game/gameobjects/player/player.s

# target to generate assembly for a file
game/gameobjects/player/player.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/gameobjects/player/player.cc.s
.PHONY : game/gameobjects/player/player.cc.s

game/input/input.o: game/input/input.cc.o

.PHONY : game/input/input.o

# target to build an object file
game/input/input.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/input/input.cc.o
.PHONY : game/input/input.cc.o

game/input/input.i: game/input/input.cc.i

.PHONY : game/input/input.i

# target to preprocess a source file
game/input/input.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/input/input.cc.i
.PHONY : game/input/input.cc.i

game/input/input.s: game/input/input.cc.s

.PHONY : game/input/input.s

# target to generate assembly for a file
game/input/input.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/input/input.cc.s
.PHONY : game/input/input.cc.s

game/input/keyboard/keyboard.o: game/input/keyboard/keyboard.cc.o

.PHONY : game/input/keyboard/keyboard.o

# target to build an object file
game/input/keyboard/keyboard.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/input/keyboard/keyboard.cc.o
.PHONY : game/input/keyboard/keyboard.cc.o

game/input/keyboard/keyboard.i: game/input/keyboard/keyboard.cc.i

.PHONY : game/input/keyboard/keyboard.i

# target to preprocess a source file
game/input/keyboard/keyboard.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/input/keyboard/keyboard.cc.i
.PHONY : game/input/keyboard/keyboard.cc.i

game/input/keyboard/keyboard.s: game/input/keyboard/keyboard.cc.s

.PHONY : game/input/keyboard/keyboard.s

# target to generate assembly for a file
game/input/keyboard/keyboard.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/input/keyboard/keyboard.cc.s
.PHONY : game/input/keyboard/keyboard.cc.s

game/physics/rigidbody/rigidbody.o: game/physics/rigidbody/rigidbody.cc.o

.PHONY : game/physics/rigidbody/rigidbody.o

# target to build an object file
game/physics/rigidbody/rigidbody.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/physics/rigidbody/rigidbody.cc.o
.PHONY : game/physics/rigidbody/rigidbody.cc.o

game/physics/rigidbody/rigidbody.i: game/physics/rigidbody/rigidbody.cc.i

.PHONY : game/physics/rigidbody/rigidbody.i

# target to preprocess a source file
game/physics/rigidbody/rigidbody.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/physics/rigidbody/rigidbody.cc.i
.PHONY : game/physics/rigidbody/rigidbody.cc.i

game/physics/rigidbody/rigidbody.s: game/physics/rigidbody/rigidbody.cc.s

.PHONY : game/physics/rigidbody/rigidbody.s

# target to generate assembly for a file
game/physics/rigidbody/rigidbody.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/physics/rigidbody/rigidbody.cc.s
.PHONY : game/physics/rigidbody/rigidbody.cc.s

game/util/box/box.o: game/util/box/box.cc.o

.PHONY : game/util/box/box.o

# target to build an object file
game/util/box/box.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/box/box.cc.o
.PHONY : game/util/box/box.cc.o

game/util/box/box.i: game/util/box/box.cc.i

.PHONY : game/util/box/box.i

# target to preprocess a source file
game/util/box/box.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/box/box.cc.i
.PHONY : game/util/box/box.cc.i

game/util/box/box.s: game/util/box/box.cc.s

.PHONY : game/util/box/box.s

# target to generate assembly for a file
game/util/box/box.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/box/box.cc.s
.PHONY : game/util/box/box.cc.s

game/util/color/color.o: game/util/color/color.cc.o

.PHONY : game/util/color/color.o

# target to build an object file
game/util/color/color.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/color/color.cc.o
.PHONY : game/util/color/color.cc.o

game/util/color/color.i: game/util/color/color.cc.i

.PHONY : game/util/color/color.i

# target to preprocess a source file
game/util/color/color.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/color/color.cc.i
.PHONY : game/util/color/color.cc.i

game/util/color/color.s: game/util/color/color.cc.s

.PHONY : game/util/color/color.s

# target to generate assembly for a file
game/util/color/color.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/color/color.cc.s
.PHONY : game/util/color/color.cc.s

game/util/point/point.o: game/util/point/point.cc.o

.PHONY : game/util/point/point.o

# target to build an object file
game/util/point/point.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/point/point.cc.o
.PHONY : game/util/point/point.cc.o

game/util/point/point.i: game/util/point/point.cc.i

.PHONY : game/util/point/point.i

# target to preprocess a source file
game/util/point/point.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/point/point.cc.i
.PHONY : game/util/point/point.cc.i

game/util/point/point.s: game/util/point/point.cc.s

.PHONY : game/util/point/point.s

# target to generate assembly for a file
game/util/point/point.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/game/util/point/point.cc.s
.PHONY : game/util/point/point.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cc.s
.PHONY : main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... game/display/sprite/sprite.o"
	@echo "... game/display/sprite/sprite.i"
	@echo "... game/display/sprite/sprite.s"
	@echo "... game/display/spritebox/spritebox.o"
	@echo "... game/display/spritebox/spritebox.i"
	@echo "... game/display/spritebox/spritebox.s"
	@echo "... game/display/transform/transform.o"
	@echo "... game/display/transform/transform.i"
	@echo "... game/display/transform/transform.s"
	@echo "... game/display/window/window.o"
	@echo "... game/display/window/window.i"
	@echo "... game/display/window/window.s"
	@echo "... game/game.o"
	@echo "... game/game.i"
	@echo "... game/game.s"
	@echo "... game/gameobjects/level/level.o"
	@echo "... game/gameobjects/level/level.i"
	@echo "... game/gameobjects/level/level.s"
	@echo "... game/gameobjects/player/player.o"
	@echo "... game/gameobjects/player/player.i"
	@echo "... game/gameobjects/player/player.s"
	@echo "... game/input/input.o"
	@echo "... game/input/input.i"
	@echo "... game/input/input.s"
	@echo "... game/input/keyboard/keyboard.o"
	@echo "... game/input/keyboard/keyboard.i"
	@echo "... game/input/keyboard/keyboard.s"
	@echo "... game/physics/rigidbody/rigidbody.o"
	@echo "... game/physics/rigidbody/rigidbody.i"
	@echo "... game/physics/rigidbody/rigidbody.s"
	@echo "... game/util/box/box.o"
	@echo "... game/util/box/box.i"
	@echo "... game/util/box/box.s"
	@echo "... game/util/color/color.o"
	@echo "... game/util/color/color.i"
	@echo "... game/util/color/color.s"
	@echo "... game/util/point/point.o"
	@echo "... game/util/point/point.i"
	@echo "... game/util/point/point.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

